services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: linkinpurry
      POSTGRES_USER: wbd
      POSTGRES_PASSWORD: passwordwbd
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "12345:5432"
    networks:
      - internal
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=postgresql://wbd:passwordwbd@db:5432/linkinpurry
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev 
    networks:
      - internal
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    environment:
      - VITE_API_URL=http://backend:3000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - internal
    restart: always

  redis:
    image: redis:latest
    networks:
      - internal
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:

networks:
  internal:
    driver: bridge